# REQUIRED CONFIG
BOT_TOKEN = ""
OWNER_ID = 0
TELEGRAM_API = 0
TELEGRAM_HASH = ""

# SEMI-REQUIRED, WE SUGGEST TO FILL IT FROM MONGODB
DATABASE_URL = ""

# OPTIONAL CONFIG
TG_PROXY = {}
USER_SESSION_STRING = ""
DOWNLOAD_DIR = "/usr/src/app/downloads/"
CMD_SUFFIX = ""
AUTHORIZED_CHATS = ""
SUDO_USERS = ""
DEFAULT_UPLOAD = "rc"
FILELION_API = ""
STREAMWISH_API = ""
EXCLUDED_EXTENSIONS = ""
INCOMPLETE_TASK_NOTIFIER = False
YT_DLP_OPTIONS = ""
USE_SERVICE_ACCOUNTS = False
NAME_SUBSTITUTE = ""
FFMPEG_CMDS = {}
UPLOAD_PATHS = {}

# INKYPINKY
DELETE_LINKS = False
FSUB_IDS = ""
TOKEN_TIMEOUT = 0
PAID_CHANNEL_ID = 0
PAID_CHANNEL_LINK = ""
SET_COMMANDS = True
METADATA_KEY = ""
WATERMARK_KEY = ""
LOG_CHAT_ID = 0
LEECH_FILENAME_CAPTION = ""
HYDRA_IP = ""
HYDRA_API_KEY = ""
INSTADL_API = ""

# GDrive Tools
GDRIVE_ID = ""
IS_TEAM_DRIVE = False
STOP_DUPLICATE = False
INDEX_URL = ""

# Rclone
RCLONE_PATH = ""
RCLONE_FLAGS = ""
RCLONE_SERVE_URL = ""
RCLONE_SERVE_PORT = 0
RCLONE_SERVE_USER = ""
RCLONE_SERVE_PASS = ""

# Mega credentials
MEGA_EMAIL = ""
MEGA_PASSWORD = ""

# Sabnzbd
USENET_SERVERS = [
    {
        "name": "main",
        "host": "",
        "port": 563,
        "timeout": 60,
        "username": "",
        "password": "",
        "connections": 8,
        "ssl": 1,
        "ssl_verify": 2,
        "ssl_ciphers": "",
        "enable": 1,
        "required": 0,
        "optional": 0,
        "retention": 0,
        "send_group": 0,
        "priority": 0,
    },
]

# Update
UPSTREAM_REPO = "https://github.com/AeonOrg/Aeon-MLTB"
UPSTREAM_BRANCH = "main"

# Leech
LEECH_SPLIT_SIZE = 0
AS_DOCUMENT = False
MEDIA_GROUP = False
USER_TRANSMISSION = False
HYBRID_LEECH = False
LEECH_FILENAME_PREFIX = ""
LEECH_DUMP_CHAT = ""
THUMBNAIL_LAYOUT = ""

# qBittorrent/Aria2c
TORRENT_TIMEOUT = 0
BASE_URL = ""
BASE_URL_PORT = 80
WEB_PINCODE = False

# Queueing system
QUEUE_ALL = 0
QUEUE_DOWNLOAD = 0
QUEUE_UPLOAD = 0

# RSS
RSS_DELAY = 600
RSS_CHAT = ""
RSS_SIZE_LIMIT = 0

# Media Tools Settings
MEDIA_TOOLS_ENABLED = True  # Enable/disable Media Tools feature

# Merge Settings
MERGE_ENABLED = False
MERGE_PRIORITY = 1
MERGE_THREADING = True
MERGE_THREAD_NUMBER = 4
MERGE_REMOVE_ORIGINAL = True
CONCAT_DEMUXER_ENABLED = True
FILTER_COMPLEX_ENABLED = False

# Merge Output Formats
MERGE_OUTPUT_FORMAT_VIDEO = "none"
MERGE_OUTPUT_FORMAT_AUDIO = "none"
MERGE_OUTPUT_FORMAT_IMAGE = "none"
MERGE_OUTPUT_FORMAT_DOCUMENT = "none"
MERGE_OUTPUT_FORMAT_SUBTITLE = "none"

# Merge Video Settings
MERGE_VIDEO_CODEC = "none"
MERGE_VIDEO_QUALITY = "none"
MERGE_VIDEO_PRESET = "none"
MERGE_VIDEO_CRF = "none"
MERGE_VIDEO_PIXEL_FORMAT = "none"
MERGE_VIDEO_TUNE = "none"
MERGE_VIDEO_FASTSTART = False

# Merge Audio Settings
MERGE_AUDIO_CODEC = "none"
MERGE_AUDIO_BITRATE = "none"
MERGE_AUDIO_CHANNELS = "none"
MERGE_AUDIO_SAMPLING = "none"
MERGE_AUDIO_VOLUME = "none"

# Merge Image Settings
MERGE_IMAGE_MODE = "none"
MERGE_IMAGE_COLUMNS = "none"
MERGE_IMAGE_QUALITY = 90
MERGE_IMAGE_DPI = "none"
MERGE_IMAGE_RESIZE = "none"
MERGE_IMAGE_BACKGROUND = "none"

# Merge Subtitle Settings
MERGE_SUBTITLE_ENCODING = "none"
MERGE_SUBTITLE_FONT = "none"
MERGE_SUBTITLE_FONT_SIZE = "none"
MERGE_SUBTITLE_FONT_COLOR = "none"
MERGE_SUBTITLE_BACKGROUND = "none"

# Merge Document Settings
MERGE_DOCUMENT_PAPER_SIZE = "none"
MERGE_DOCUMENT_ORIENTATION = "none"
MERGE_DOCUMENT_MARGIN = "none"

# Merge Metadata Settings
MERGE_METADATA_TITLE = "none"
MERGE_METADATA_AUTHOR = "none"
MERGE_METADATA_COMMENT = "none"
