name: Deploy to Heroku

on:
  workflow_dispatch:
    inputs:
      HEROKU_APP_NAME:
        description: "Heroku App name"
        required: true
      HEROKU_API_KEY:
        description: "Heroku API key"
        required: true
      HEROKU_EMAIL:
        description: "Heroku email address"
        required: true
      HEROKU_TEAM_NAME:
        description: "Heroku Team Name"
        required: false
      BOT_TOKEN:
        description: "Telegram bot token"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Delete unnecessary directories and files
        run: |
          # Directories to delete
          for dir in bot qBittorrent web; do
            if [ -d "./$dir" ]; then
              echo "Deleting directory: $dir"
              rm -rf ./$dir
            else
              echo "Directory not found: $dir"
            fi
          done

          # Delete aria.sh if it exists
          if [ -f "./aria.sh" ]; then
            echo "Deleting file: aria.sh"
            rm -f ./aria.sh
          else
            echo "File not found: aria.sh"
          fi

      - name: Deploy to Heroku
        uses: 5hojib/heroku-deploy-action@v2
        with:
          heroku_api_key: ${{inputs.HEROKU_API_KEY}}
          heroku_app_name: ${{inputs.HEROKU_APP_NAME}}
          heroku_email: ${{inputs.HEROKU_EMAIL}}
          team: ${{ inputs.HEROKU_TEAM_NAME != '' && format('{0}', inputs.HEROKU_TEAM_NAME) || '' }}
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "eu"
        env:
          HD_OWNER_ID: 7716048556
          HD_TELEGRAM_API: 23241238
          HD_TELEGRAM_HASH: e6ff6e3068dbea75500865ac49c3608f
          HD_DATABASE_URL: mongodb+srv://tellymirror:bot@tellymirror.6euwucp.mongodb.net/?retryWrites=true&w=majority&appName=TellyMirror
          HD_BOT_TOKEN: ${{inputs.BOT_TOKEN}}
          HD_HEROKU_APP_NAME: ${{inputs.HEROKU_APP_NAME}}
          HD_HEROKU_API_KEY: ${{inputs.HEROKU_API_KEY}}
